### ISSUE TITLE
compile error while installing package

### ISSUE THREAD

**Issue by rogerallen** [sanel/monroe#13]
I don't actually know if this is an issue or not, because monroe seems to work.  But, I thought I'd mention it just in case it is.

When I installed from melpa-stable (you might want to mention this repo in docs), I got the following output...

```
Compiling file /Users/rallen/.emacs.d/elpa/monroe-0.3.0/monroe-pkg.el at Sat Aug  6 08:07:53 2016
Entering directory `/Users/rallen/.emacs.d/elpa/monroe-0.3.0/'

Compiling file /Users/rallen/.emacs.d/elpa/monroe-0.3.0/monroe.el at Sat Aug  6 08:07:53 2016

In monroe-dbind-response:
monroe.el:114:16:Warning: reference to free variable `for'
monroe.el:114:20:Warning: reference to free variable `key'
monroe.el:114:24:Warning: reference to free variable `in'
monroe.el:115:16:Warning: reference to free variable `collect'
monroe.el:233:1:Error: Symbol's value as variable is void: for
```

So, I initially thought there was a failure, but it starts up & seems to work for me.

This is on Mac OS X 10.10.5 with Emacs 24.5.1

**Comment by sanel** [comment]
Thanks for report! Looks like `loop` and members got moved in `cl` module for newer Emacs-es, which requires explicit inclusion (albeit it is implicitly included, with a bunch of warnings). There is already PR #12 for this, I'm going to apply during the next week.

**Comment by sanel** [comment]
Applied patch and pushed it as new release - `0.3.1`. Let me know if you find any issues.

**Comment by rogerallen** [comment]
works for me.  thanks!
