### ISSUE TITLE
monroe-connect should pass an integer as the port number to open-network-stream

### ISSUE THREAD

**Issue by destroyhimmyrobots** [sanel/monroe#14]
System Details:

- Windows 10, 64-bit
- GNU Emacs 24.5.1 (i686-pc-mingw32), built on 2015-04-11

The documentation for the function `open-network-stream` called by by `monroe-connect` states:

    SERVICE is the name of the service desired, 
    or an integer specifying a port number to connect to.

Because `monroe-connect` passes a string to the *SERVICE* parameter of `open-network-stream`, the following error is thrown:

    Unknown service: 7888

One can correct this by passing an integer port number to `open-network-stream`. Here's a quick hack to demonstrate working arguments:

```
(advice-add #'open-network-stream
            :filter-args
            (lambda (r) (setf (elt r 3) (string-to-int (elt r 3))) r))
```

**Comment by sanel** [comment]
Thanks for catching it!

Can you please try changes I pushed in fd742ee?

**Comment by destroyhimmyrobots** [comment]
LGTM! Thank you for the swift patch.
