### ISSUE TITLE
Mode hooks

### ISSUE THREAD

**Issue by danielsz** [sanel/monroe#21]
I'd love to be able to add custom elisp via the standard Emacs mode hook facility. 

With Cider, for example, I have the following:

```emacs
(add-hook 'cider-repl-mode-hook (lambda () (abbrev-mode 1)))
```

Thanks for listening!

**Comment by sanel** [comment]
Will `monroe-mode-hook` and `monroe-interaction-mode-hook` be suitable for you?

`monroe-mode-hook` is called when new connection is made in REPL buffer and `monroe-interaction-mode-hook` is called when you open anything that invokes "Monroe" mode (like .clj/.cljs files and so on).

**Comment by sanel** [comment]
These aren't documented in README, which should be changed...

**Comment by danielsz** [comment]
Yes, it's perfect, actually. Thank you so much! (I should have looked more closely at the source code)
```emacs
(add-hook 'monroe-mode-hook (lambda () (abbrev-mode 1)))
```

**Comment by danielsz** [comment]
Oh, right! 

I actually looked at the code a while back and indeed couldn't find it. Thank you for explaining!
 :+1:
