### ISSUE TITLE
Add monroe fork for Arcadia in README

### ISSUE THREAD

**Issue by sanel** [sanel/monroe#30]
Fork is here: https://github.com/Saikyun/monroe

**Comment by technomancy** [comment]
Would it make sense to identify all the places where monroe assumes the remote side is a Clojure server and provide an extensible interface so alternatives can be provided without forking monroe?

**Comment by sanel** [comment]
This is great idea, but let's see how much change is planned in this forked version. Maybe @Saikyun wants to explore things outside monroe scope...

**Comment by Saikyun** [comment]
I do plan on adding some support for step debugging which will depend heavily on Arcadia's implementation of breakpoints, but it might still make sense to try to unify the similar parts, and treat the differing parts like plugins or such. I'll get back when I've added what I feel is most important, and we can see if miracle is still similar enough to monroe. :)
