### ISSUE TITLE
Stacktrace lost after first exception

### ISSUE THREAD

**Issue by yayitswei** [sanel/monroe#8]
After the first exception, the stacktraces no longer display in the buffer for subsequent exceptions. Do you know what's causing this?

```
user=> uehotanuehaostnuh
CompilerException java.lang.RuntimeException: Unable to resolve symbol: uehotanuehaostnuh in this context, compiling:(/private/var/folders/4x/mt4fz1c56797b2c8bs5c8x1m0000gn/T/form-init516450021019911153.clj:1:195) 
user=> clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: uehotanuehaostnuh in this context, compiling:(/private/var/folders/4x/mt4fz1c56797b2c8bs5c8x1m0000gn/T/form-init516450021019911153.clj:1:195)
                                Compiler.java:6464 clojure.lang.Compiler.analyze
                                Compiler.java:6406 clojure.lang.Compiler.analyze
...
nil
user=> uhtenoaseuhau
user=> nil
user=> 
```

**Comment by yayitswei** [comment]
A bit more info: the problem seems to crop up after running `lein uberjar; lein run`. It goes away if I clean and then run `lein run`.

Do you know why creating an uberjar would have an effect on whether exceptions are printed?

Also, a side question: if you left `monroe-detail-stacktraces` as false, how do view the last exception's stacktrace, if you decide to investaget further?

**Comment by sanel** [comment]
Honestly, not sure. I presume that `lein run` would pick up jar generated by uberjar and maybe uberjar would strip out the code or do some optimizations (dumb guessing). Can you check with Cider please and let me know does it behave the same?

> Also, a side question: if you left monroe-detail-stacktraces as false, how do view the last exception's stacktrace, if you decide to investaget further?

Monroe uses some tricks to get the full stacktrace from the last exception (by trying to load `clj-stacktrace` then fallback to `clojure.stacktrace`), but in general calling something like:

```clojure
(clojure.stacktrace/print-stack-trace *e)
```

will do the job

**Comment by sanel** [comment]
Sorry, I accidentally closed this ticked :) Reopening it again.

**Comment by yayitswei** [comment]
Nice, `(clojure.stacktrace/print-stack-trace *e)` works for me. A shortcut for that might be nice-- how would I go about writing one?

I'll check with Cider when I get around to installing and configuring it (part of the reason for using Monroe was the ease of started). For now, feel free to close the issue since it's nonblocking.

Thanks for your help @sanel!

**Comment by sanel** [comment]
>  A shortcut for that might be nice-- how would I go about writing one?

You can assign key to this code:

```clojure
  (monroe-input-sender
   (get-buffer-process monroe-repl-buffer)
   "(clojure.stacktrace/print-stack-trace *e))"))
```

This is temporal solution, as things could be changed in the future when multiple session support is added.

> Thanks for your help

You're welcome! Let me know if you find other issues.
